### ISSUE TITLE
Examples Are Crashing?

### ISSUE THREAD

**Issue by Correlander** [thedead2/customadvancements#7]
Version: customadvancements-1.19.2-5.7.3.jar
[crash-2023-09-19_09.03.34-fml.txt](https://github.com/thedead2/customadvancements/files/12661219/crash-2023-09-19_09.03.34-fml.txt)
Crashlog uploaded above
This was working before, so I really am not sure what changed, but now on launch I get this problem. Even example advancements are erroring.
It is saying there is an unacceptable character in the path to the example folder, even though there isn't...?

**Comment by thedead2** [comment]
Hi thanks for reaching out, the problem is that your resource location uses an uppercase character `customadvancements:Example/back_to_the_roots.json`.
Unfortunately resource locations can only have lowercase characters.
Therefore you have to replace the uppercase E with a lowercase e.
In a previous version of the mod, the resource locations were created differently automatically converting all characters to lowercase. The new version does not do this anymore as changing the characters inside the code can cause some issues.
Hope this helps.

**Comment by Correlander** [comment]
Ah okay. Thank you for the prompt reply.

**Comment by thedead2** [comment]
No problem, I've now added a short section to the [wiki](https://github.com/thedead2/customadvancements/wiki) on how a resource location must look like.
